### ISSUE TITLE
Is ok to contribute?

### ISSUE THREAD

**Issue by Bartmax** [ElasticEmail/ElasticEmail.WebApiClient-csharp-core#2]
I can see some PR that I think I can tackle on the ASP.NET Core implementation of the API client.

Is it ok to send a PR for better C# conventions and normal usage?

The improvements I can see that can be done are:

1) Refactor and split code.
2) Switch to the most compatible netstandard2 instead of 1.6 and drop the not-needed net46
3) Unit tests for operations
4) Use httpclient factory AND Refit
5) Implement retry and resilence mechanisms
6) Better exception handling

and pretty sure there are more that can be done, but there is a lot of work already.

Let me know if you are interested.

**Comment by ppodolak** [comment]
Hi @Bartmax , thx for the proposition. Today we realsed beta of  the new RESTful api version and this library will be deprecated.  You can test new version here https://github.com/ElasticEmail/elasticemail-RESTful-api-csharp
